# Generated by Django 3.2.10 on 2022-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_uploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='base.Skill'),
        ),
    ]
